// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvrmghdrpdwbixqeqipc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cm1naGRycGR3Yml4cWVxaXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyNDQyMzQsImV4cCI6MjA2NzgyMDIzNH0.9BbLJtZ_tl_Bu1foLvkNRzILrTASl8Ll6vc00t81gCc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});